const severityConfig = {
  1: {
    label: "Resuscitation",
    sublabel: "Immediate life-saving intervention required",
    chip: "bg-rose-600 text-rose-50",
    card: "border-rose-400/50 bg-rose-950/60 text-rose-100",
    meter: "from-rose-500 to-red-700",
    glow: "shadow-rose-500/30",
    icon: "🔴",
  },
  2: {
    label: "Emergent",
    sublabel: "Time-critical condition — attend within 10 min",
    chip: "bg-orange-600 text-orange-50",
    card: "border-orange-400/50 bg-orange-950/60 text-orange-100",
    meter: "from-orange-400 to-orange-600",
    glow: "shadow-orange-500/30",
    icon: "🟠",
  },
  3: {
    label: "Urgent",
    sublabel: "Significant condition — attend within 30 min",
    chip: "bg-yellow-600 text-yellow-50",
    card: "border-yellow-400/50 bg-yellow-950/60 text-yellow-100",
    meter: "from-yellow-400 to-yellow-600",
    glow: "shadow-yellow-500/25",
    icon: "🟡",
  },
  4: {
    label: "Less Urgent",
    sublabel: "Non-critical — attend within 60 min",
    chip: "bg-lime-600 text-lime-50",
    card: "border-lime-400/50 bg-lime-950/60 text-lime-100",
    meter: "from-lime-400 to-lime-600",
    glow: "shadow-lime-500/20",
    icon: "🟢",
  },
  5: {
    label: "Non-Urgent",
    sublabel: "Minor concern — standard queue",
    chip: "bg-emerald-600 text-emerald-50",
    card: "border-emerald-400/50 bg-emerald-950/60 text-emerald-100",
    meter: "from-emerald-400 to-emerald-700",
    glow: "shadow-emerald-500/20",
    icon: "🟢",
  },
};

const fallbackFieldOptions = {
  site_id: [{ value: "SITE-0001", label: "Central Emergency Department" }],
  nurse_id: [{ value: "self", label: "Self Registration" }],
  sex: [
    { value: "M", label: "Male" },
    { value: "F", label: "Female" },
  ],
  language: [
    "Arabic",
    "English",
    "Estonian",
    "Finnish",
    "Other",
    "Russian",
    "Somali",
    "Swedish",
  ].map((value) => ({ value, label: value })),
  insurance_type: [
    "military",
    "none",
    "private",
    "public",
    "unknown",
  ].map((value) => ({ value, label: value.replace("_", " ").replace(/\b\w/g, (match) => match.toUpperCase()) })),
  arrival_mode: [
    "ambulance",
    "brought_by_family",
    "helicopter",
    "police",
    "transfer",
    "walk-in",
  ].map((value) => ({ value, label: value.replace(/-/g, " ").replace(/_/g, " ").replace(/\b\w/g, (match) => match.toUpperCase()) })),
  transport_origin: [
    "home",
    "nursing_home",
    "other_hospital",
    "outdoor",
    "public_space",
    "school",
    "workplace",
  ].map((value) => ({ value, label: value.replace(/_/g, " ").replace(/\b\w/g, (match) => match.toUpperCase()) })),
  pain_location: [
    "abdomen",
    "back",
    "chest",
    "extremity",
    "head",
    "multiple",
    "none",
    "pelvis",
    "unknown",
  ].map((value) => ({ value, label: value.replace(/\b\w/g, (match) => match.toUpperCase()) })),
  mental_status_triage: [
    "agitated",
    "alert",
    "confused",
    "drowsy",
    "unresponsive",
  ].map((value) => ({ value, label: value.replace(/\b\w/g, (match) => match.toUpperCase()) })),
};

function buildInitialFormData(fieldOptions = fallbackFieldOptions) {
  return {
    site_id: fieldOptions.site_id?.[0]?.value || "SITE-0001",
    nurse_id: fieldOptions.nurse_id?.[0]?.value || "self",
    name: "",
    age: "",
    sex: "M",
    language: fieldOptions.language?.[1]?.value || "English",
    insurance_type: fieldOptions.insurance_type?.[3]?.value || "public",
    num_active_medications: "",
    num_comorbidities: "",
    weight_kg: "",
    height_cm: "",
    arrival_mode: fieldOptions.arrival_mode?.[5]?.value || "walk-in",
    transport_origin: fieldOptions.transport_origin?.[0]?.value || "home",
    pain_location: fieldOptions.pain_location?.[7]?.value || "unknown",
    mental_status_triage: fieldOptions.mental_status_triage?.[1]?.value || "alert",
    chief_complaint_raw: "",
    heart_rate: "",
    respiratory_rate: "",
    spo2: "",
    systolic_bp: "",
    diastolic_bp: "",
    temperature_c: "",
    pain_score: "",
    gcs_total: "",
  };
}

export { buildInitialFormData, fallbackFieldOptions, severityConfig };
